### ISSUE TITLE
Error: SHA1 not changed

### ISSUE THREAD

**Issue by sariya** [MRCIEU/MRInstruments#6]
Hi there, 
when I try to install MRInstruments using devtools, I get error as:

`Skipping install of 'MRInstruments' from a github remote, the SHA1 (b5efc600) has not changed since last install.`

I use `force=TRUE` however.

**Comment by remlapmot** [comment]
This is not an error. You do not need to force the install.

This output message is simply telling you that you already have the package installed and your installed version up to date with the version on the GitHub master branch here.

**Comment by sariya** [comment]
Got it, thanks.
